### ISSUE TITLE
Feature request: Reduce Visible Part of Table Cell to Max Character Count with Full Text on Hover

### ISSUE THREAD

**Issue by berntpopp** [berntpopp/VNtyper#42]
**Summary:**

In the current implementation of the cohort summary report, the contents of some table cells (e.g., those containing sequences or long text) can be too lengthy, making the table difficult to read and causing it to take up too much horizontal space. This issue proposes truncating the content displayed in these cells to a maximum character count, with an ellipsis (`...`) indicating that the content has been truncated. Additionally, the full text should be visible when a user hovers over the truncated cell.

**Details:**

- **Feature Request:** Apply CSS properties such as `text-overflow: ellipsis`, `white-space: nowrap`, and `overflow: hidden` to reduce the visible part of a table cell to a maximum character count.
- **Affected Cells:** This would primarily affect cells that contain long sequences, long text descriptions, or other lengthy content.
- **Desired Behavior:** 
  - When a cell's content exceeds the maximum character count, it should be truncated with an ellipsis (`...`) to indicate that there is more content that is not visible.
  - The full text should be displayed in a tooltip when the user hovers over the cell.
- **Example:**
  - Current: `TGGGGGGGCGGGTG...`
  - Proposed: `TGGGGGGG...` (full text on hover)

**Proposed Solution:**

1. **CSS Changes:**
   - Apply the following CSS rules to the affected table cells:
     ```css
     .table td {
         white-space: nowrap;
         overflow: hidden;
         text-overflow: ellipsis;
         max-width: 150px; /* Adjust as needed */
         cursor: pointer;
     }
     .table td:hover {
         overflow: visible;
         white-space: normal;
         max-width: none;
         position: relative;
         z-index: 10;
         background-color: #fff;
         border: 1px solid #ddd;
     }
     ```
   - The `max-width` value can be adjusted depending on the desired maximum character count.
   - Use `cursor: pointer;` to indicate that hovering will show more content.

2. **Tooltip:**
   - Ensure that the full text is visible when hovering over the truncated cell by using the `hover` state to temporarily remove the truncation.

3. **Max Character Count:**
   - Determine an appropriate maximum character count for cells based on the layout and design requirements (e.g., 10–20 characters).

**Additional Considerations:**

- **Responsiveness:** Ensure that the truncation works well on different screen sizes and resolutions.
- **Accessibility:** Consider how screen readers will interpret the truncated content and whether alternative text or additional descriptions are necessary for accessibility.

**Impact:**

- **User Experience:** Improved readability of tables with long content, resulting in a cleaner and more user-friendly interface.
- **Performance:** Minimal impact on performance, as the changes involve only CSS properties.
